from typing import Optional, Dict, Any, Tuple, Type
from types import TracebackType
from dataclasses import dataclass
import hashlib
import os
import base64
import secrets
import urllib.parse

import httpx
from riotskillissue.core.http import RiotAPIError


@dataclass
class RsoConfig:
    client_id: str
    client_secret: str
    redirect_uri: str
    provider: str = "https://auth.riotgames.com"


@dataclass
class TokenResponse:
    access_token: str
    refresh_token: str
    id_token: str
    expires_in: int
    scope: str


def _generate_pkce() -> Tuple[str, str]:
    """Generate a PKCE code_verifier and code_challenge (S256)."""
    verifier = base64.urlsafe_b64encode(os.urandom(32)).rstrip(b"=").decode("ascii")
    digest = hashlib.sha256(verifier.encode("ascii")).digest()
    challenge = base64.urlsafe_b64encode(digest).rstrip(b"=").decode("ascii")
    return verifier, challenge


class RsoClient:
    """Helper for Riot Sign-On (OAuth2) with PKCE and CSRF support."""

    def __init__(self, config: RsoConfig):
        self.config = config
        self.http = httpx.AsyncClient()

    async def close(self) -> None:
        """Close the underlying HTTP client."""
        await self.http.aclose()

    async def __aenter__(self) -> "RsoClient":
        return self

    async def __aexit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc_val: Optional[BaseException],
        exc_tb: Optional[TracebackType],
    ) -> None:
        await self.close()

    def get_auth_url(
        self,
        scope: str = "openid",
        *,
        use_pkce: bool = True,
    ) -> Dict[str, str]:
        """Generate the login URL for the user.

        Returns a dict with keys:
        - ``url``: The full authorization URL to redirect the user to.
        - ``state``: CSRF token that **must** be validated on callback.
        - ``code_verifier``: PKCE verifier to pass to :meth:`exchange_code`
          (only present when *use_pkce* is ``True``).
        """
        state = secrets.token_urlsafe(32)
        params: Dict[str, str] = {
            "client_id": self.config.client_id,
            "redirect_uri": self.config.redirect_uri,
            "response_type": "code",
            "scope": scope,
            "state": state,
        }

        result: Dict[str, str] = {"state": state}

        if use_pkce:
            verifier, challenge = _generate_pkce()
            params["code_challenge"] = challenge
            params["code_challenge_method"] = "S256"
            result["code_verifier"] = verifier

        base = f"{self.config.provider}/authorize"
        result["url"] = f"{base}?{urllib.parse.urlencode(params)}"
        return result

    async def exchange_code(
        self,
        code: str,
        *,
        code_verifier: Optional[str] = None,
    ) -> TokenResponse:
        """Exchange an authorization code for tokens.

        Args:
            code: The authorization code from the callback.
            code_verifier: The PKCE verifier generated by :meth:`get_auth_url`.
        """
        url = f"{self.config.provider}/token"

        data: Dict[str, str] = {
            "grant_type": "authorization_code",
            "code": code,
            "redirect_uri": self.config.redirect_uri,
        }
        if code_verifier:
            data["code_verifier"] = code_verifier

        resp = await self.http.post(
            url,
            auth=(self.config.client_id, self.config.client_secret),
            data=data,
        )

        if not resp.is_success:
            raise RiotAPIError(resp.status_code, resp.text, resp)

        return TokenResponse(**resp.json())

    async def refresh_token(self, refresh_token: str) -> TokenResponse:
        """Get new access token using a refresh token."""
        url = f"{self.config.provider}/token"

        resp = await self.http.post(
            url,
            auth=(self.config.client_id, self.config.client_secret),
            data={
                "grant_type": "refresh_token",
                "refresh_token": refresh_token,
            },
        )

        if not resp.is_success:
            raise RiotAPIError(resp.status_code, resp.text, resp)

        return TokenResponse(**resp.json())
